### ISSUE TITLE
Implement XEP-0280: Message Carbons

### ISSUE THREAD

**Issue by maufl** [TelepathyIM/telepathy-gabble#2]
I just bought Sailfish OS for a Sony Xperia X. It is using Telepathy as communication framework and I really like how integrated it is. Unfortunately telepathy-gabble does not support message carbons, so my chat is out of sync with the other devices.

**Comment by detrout** [comment]
We haven't had time to merge it but fairly complete patches are over here:

https://github.com/noonien-d/telepathy-gabble/tree/XEP-0280+XEP-0333
I don't remember if that needed wocky patches or not https://github.com/noonien-d/wocky

Given my current progress I'm guessing I'll have time to work on merging them in a month or two.

**Comment by d9h20f** [comment]
For the record: http://devel.kondorgulasch.de/telepathy-gabble/

**Comment by maufl** [comment]
Well this is probably everything I'm looking for! Is there a reason it is not merged upstream and enabled by default?

**Comment by detrout** [comment]
Its not merged because the original telepathy team lost funding and was frustrated with the problems of multi protocol chat clients.

The few people who are still interested don't have much free time.

**Comment by detrout** [comment]
@d9h20f That's a nicely organized  collection of patches you've got there.... 

You know... code review is a lot easier with github than with bugzilla... might you be interested in putting together some pull requests?

**Comment by d9h20f** [comment]
You'll have to ask @noonien-d, I'm not related to the patches or site in any way.

**Comment by noonien-d** [comment]
You'll need the wocky patches for XEP-0198 Stream Management, everything else should work with stock wocky.
Note that the more recent patches are for the 0.18.4 branch, the ones without prefix are for 0.19~. 
I just pushed the XEP-0280/333 patch for 0.18, seems I forgot to publish that one.

**Comment by maufl** [comment]
@noonien-d Your telepathy-gabble-plus looks awesome. Can I incentivize you to upstream it? My C is unfortunately not good and my knowledge of Gome-style C even less so.

**Comment by rufferson** [comment]
uhm, I've started carbons implementation as well last year, although it's incomplete yet. Nevertheless i have pending roster-version and Jingle-FT commits. Someone needs probably to start pulling some commits at least to have a common base (eg stream features processing)

**Comment by noonien-d** [comment]
I filed a pull request: https://github.com/TelepathyIM/telepathy-gabble/pull/3

**Comment by rufferson** [comment]
You probably need to rebase it first against master's HEAD? As it has conflicts

**Comment by noonien-d** [comment]
This issue should be closed, as #3 has been merged

**Comment by Kaffeine** [comment]
> This issue should be closed, as #3 has been merged

Right!
